### ISSUE TITLE
java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by Edijae** [lipisha/lipisha-java-sdk#4]
I'm getting timeout exception when trying to complete card transaction.

```
lipishaClient = new LipishaClient(API_KEY,API_SIGNATURE,BASE_URL);
lipishaClient.completeCardTransaction(transactionIndex,transReference).execute();
```
Stack-trace

```
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:212)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
	at okhttp3.RealCall.getResponse(RealCall.java:244)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
```

**Comment by tised** [comment]
Same error for me, any solutions?

**Comment by Edijae** [comment]
I solved by increasing timeout value. Just override the timeout value

**Comment by tised** [comment]
By the way, it will be great if you will increase retrofit versions,
because it's conflicting for example in my android project.
The problem is that I'm using 2.3.0 and lipisha have 2.0.3 and it's pretty
old

**Comment by reenezden** [comment]
@Edijae how did youoverride the timeout value?

**Comment by Edijae** [comment]
By cloning the project and including it in your project. Then you can
follow the method calls until you get to retrofit instance creation. From
there you can override anything you want
